[[established_account]]
vp = "vp_user"
threshold = 2
public_keys = ["tpknam1qzctf9dlf4r27y4x9gj2xqsx4ukt5ljc9t5g4acv2gkm9meq402mx8aupqr", "tpknam1qqvkh795paq329jvh2ale7k58ufwymr3m8y2lspf67d92ud7gqrukfyf3ys", "tpknam1qqty58m0w899n9nuuxe7ml3cgywtq05x0d8vckhj0sepfpdyd5ytypzcrpt"]
