[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qzwqar4rydp4nsn4j2xj8hef8jknh3dv7dv99snqd5lfkj8p4pa2vny7cph"]

[[validator_account]]
address = "tnam1q9tguf7ppxudvgjpkl5u80el28kyhdxhtspk26hl"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "192.168.0.1:26656"

[validator_account.consensus_key]
pk = "tpknam1qqagysdt83h9z90mrdvdx70x4tccx4hprxq783hyanjt8c9jnew825t6v42"
authorization = "signam1qzgu30w6m04zqgw9f74rmd5f528fksv5ryg8j0rcwwpsu8dnhceu93exrynnar7pk76d46d8t3c0af26hr2lhscvntt6475v9gc7pxqv57ajv9"

[validator_account.protocol_key]
pk = "tpknam1qrp3tmqla3m0ndj2kjvvq4v5lmcn7kzw4gemrxa35ypvcz8ajt32cak5ku9"
authorization = "signam1qrukatlazqcje6ka20sh6e0qs5590t7q3nfekqvnnu92nje5dnceu3m5pycuw39lge0xhgezqp4egwrawh68aautscm4wdvgqx72ytcgm8kctp"

[validator_account.tendermint_node_key]
pk = "tpknam1qrcsgvn6036kvaxzeqtg4l9n28d0pzdyj8nr42vwyu8cq6jjdau82n9r46q"
authorization = "signam1qqufnwgk5yzhzh0zwfk040xv09tj5ftt2k8xtsesnd6y000rrjdu85h3prjknagmtn349wndzgpcv8lywj2n5xhwfq4l39hahjqakjs8v26qdc"

[validator_account.eth_hot_key]
pk = "tpknam1qyp82gn922f2tgcn7ehden9u34enungvlrvryc0vaxn3uedzl0mkews60pezk"
authorization = "signam1q84tumwndx6wvwmtxzpcqyzcwpf5t4zyc85a4s8xtvnjg6w9d8fdcguekpqhrapdqcznwj0l0ye2e93tdsmcu4xdhfzc7vh0l0c2qrjqqy4ymz60"

[validator_account.eth_cold_key]
pk = "tpknam1qypk5glm9z4j2kxse9jc9as70u8u2c7zrm3hxh7f52x0grfl36er2dcc5h03a"
authorization = "signam1q8kgxk2gy8lrgmvzugu2jfggkkv46tz8n4k0xy6p5667pjsv8z0y5uv9g2zmzh02gj0j5eyujttttlu3gnwv2v67ar3sn5yx7jhdtc2sqyg3gjn7"

[validator_account.metadata]
email = "s4@gmail.com"

[validator_account.signatures]
tpknam1qzwqar4rydp4nsn4j2xj8hef8jknh3dv7dv99snqd5lfkj8p4pa2vny7cph = "signam1qpfhzg0karjwxcnten2rwund2lvcajzptp026qw83e5kdrtftv6dfcrqvf37qfy6y493tsr7z6xtuchwfg2hwfv34xczwfu4qk4jlkqwsh3kxd"

[[bond]]
source = "tnam1q9tguf7ppxudvgjpkl5u80el28kyhdxhtspk26hl"
validator = "tnam1q9tguf7ppxudvgjpkl5u80el28kyhdxhtspk26hl"
amount = "0.1"

[bond.signatures]
tpknam1qzwqar4rydp4nsn4j2xj8hef8jknh3dv7dv99snqd5lfkj8p4pa2vny7cph = "signam1qq3y9rdawx2f5llst5qalta79peg4cl96ffdq0kr728tjeptv3jva8mr9g2u86rtwjqktkjhzap586wkg8459hwhmyu2up8w7kaaplcrn7nq8y"
