version: "3.8"

services:
  # validator node
  namada-1:
    restart: unless-stopped
    hostname: namada-1
    image: namada:${NAMADA_TAG}
    entrypoint: [ "sh", "/docker-entrypoint-scripts.d/start-node.sh" ]
    volumes:
      - ../config/local-namada/start-node.sh:/docker-entrypoint-scripts.d/start-node.sh
      # chain data location; change this to an appropriate location on your system
      - $HOME/chaindata/namada-1:/root/.local/share/namada
      - namada-shared:/root/.namada-shared
      - ../config/local-namada/genesis:/genesis:ro
      - ../config/local-namada/make_balances.py:/scripts/make_balances.py
      - /usr/share/nginx/html:/output
      - ../config/local-namada/index.html:/index.html
    environment:
      - P2P_PORT=${P2P_PORT}
      - EXTIP=${EXTIP}
      - SERVE_PORT=${SERVE_PORT}
      - NAMADA_TAG=${NAMADA_TAG}
      - CHAIN_PREFIX=${CHAIN_PREFIX:-luminara}
      - DOMAIN=${DOMAIN:-knowable.run}
      - SELF_BOND_AMT=${SELF_BOND_AMT:-1000000000}
      - GENESIS_DELAY_MINS=${GENESIS_DELAY_MINS:-1}
    ports:
      - "${P2P_PORT}:26656" # p2p
      # - "26657" # http rpc
      - "8082:8123" # configs server

  namada-2:
    # rpc node
    restart: unless-stopped
    hostname: namada-2
    image: namada:${NAMADA_TAG}
    entrypoint: [ "sh", "/docker-entrypoint-scripts.d/start-node.sh" ]
    volumes:
      - ../config/local-namada/start-node.sh:/docker-entrypoint-scripts.d/start-node.sh
      # chain data location; change this to an appropriate location on your system
      - $HOME/chaindata/namada-2:/root/.local/share/namada
      - namada-shared:/root/.namada-shared
    environment:
      - CHAIN_PREFIX=${CHAIN_PREFIX:-luminara}
      - DOMAIN=${DOMAIN:-knowable.run}
      - SELF_BOND_AMT=${SELF_BOND_AMT:-1000000000}
      - GENESIS_DELAY_MINS=${GENESIS_DELAY_MINS:-1}
    ports:
      - "26656" # p2p
      # - "26657" # http rpc
      - "${RPC_PORT:-26657}:26657" # http rpc
      - "26660:26660" # prometheus metrics

  namada-3:
    # validator node
    restart: unless-stopped
    hostname: namada-3
    image: namada:${NAMADA_TAG}
    entrypoint: [ "sh", "/docker-entrypoint-scripts.d/start-node.sh" ]
    volumes:
      - ../config/local-namada/start-node.sh:/docker-entrypoint-scripts.d/start-node.sh
      # chain data location; change this to an appropriate location on your system
      - $HOME/chaindata/namada-3:/root/.local/share/namada
      - namada-shared:/root/.namada-shared
    environment:
      - CHAIN_PREFIX=${CHAIN_PREFIX:-luminara}
      - DOMAIN=${DOMAIN:-knowable.run}
      - SELF_BOND_AMT=${SELF_BOND_AMT:-1000000000}
      - GENESIS_DELAY_MINS=${GENESIS_DELAY_MINS:-1}
    ports:
      - "26656" # p2p
      - "26657"
      # - "${RPC_PORT:-26657}:26657" # http rpc
      # - "26660:26660"

volumes:
  # shared 'network directory' for genesis txs etc that need to be shared between validators when generating genesis files
  namada-shared:
